version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.14
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - npm install
  build:
    commands:
      - echo testing...
      - echo building...
      - ng build --aot
  post_build:
    commands:
      - echo Build of BSC Angular App completed on `date`
artifacts:
  files:
    - dist/**/*